<?php

namespace Database\Seeders;

use App\Models\Flight;
use Illuminate\Database\Seeder;

/**
 * earningMileStatement.pdf'ten gelen uçuşlarda mesafe (km) bilgisi yoktu.
 * Bu seeder, her uçuşun havalimanı koordinatlarından büyük daire (haversine)
 * mesafesini hesaplayıp mevcut Flight kayıtlarını flight_date+from_city+to_city
 * eşleşmesiyle günceller. Kuş uçuşu mesafedir, gerçek uçuş rotası biraz daha
 * uzun olabilir. 22.05.2016 tarihli "Bilinmiyor (TEQ)" kaydı IATA kodu
 * çözülemediği için atlandı, mesafesi boş kalır.
 */
class FlightDistanceBackfillSeeder extends Seeder
{
    public function run(): void
    {
        $updates = [
            ['flight_date' => '2003-11-04', 'from_city' => 'Antalya', 'to_city' => 'İstanbul', 'distance_km' => 518],
            ['flight_date' => '2003-11-19', 'from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'distance_km' => 1978],
            ['flight_date' => '2004-01-17', 'from_city' => 'Ankara', 'to_city' => 'İstanbul', 'distance_km' => 380],
            ['flight_date' => '2004-01-17', 'from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'distance_km' => 1978],
            ['flight_date' => '2012-08-21', 'from_city' => 'İstanbul', 'to_city' => 'Singapur', 'distance_km' => 8678],
            ['flight_date' => '2012-08-27', 'from_city' => 'Singapur', 'to_city' => 'İstanbul', 'distance_km' => 8678],
            ['flight_date' => '2012-09-16', 'from_city' => 'İstanbul', 'to_city' => 'Ankara', 'distance_km' => 380],
            ['flight_date' => '2012-09-18', 'from_city' => 'Kayseri', 'to_city' => 'İstanbul', 'distance_km' => 638],
            ['flight_date' => '2013-07-01', 'from_city' => 'İstanbul', 'to_city' => 'Cenova', 'distance_km' => 1656],
            ['flight_date' => '2013-07-08', 'from_city' => 'Cenova', 'to_city' => 'İstanbul', 'distance_km' => 1656],
            ['flight_date' => '2014-01-30', 'from_city' => 'İstanbul', 'to_city' => 'Cenova', 'distance_km' => 1656],
            ['flight_date' => '2014-02-10', 'from_city' => 'Cenova', 'to_city' => 'İstanbul', 'distance_km' => 1656],
            ['flight_date' => '2014-10-19', 'from_city' => 'İstanbul', 'to_city' => 'Cenova', 'distance_km' => 1656],
            ['flight_date' => '2014-10-26', 'from_city' => 'Cenova', 'to_city' => 'İstanbul', 'distance_km' => 1656],
            ['flight_date' => '2014-11-28', 'from_city' => 'Sao Paulo', 'to_city' => 'İstanbul', 'distance_km' => 10559],
            ['flight_date' => '2015-05-16', 'from_city' => 'İstanbul', 'to_city' => 'Napoli', 'distance_km' => 1211],
            ['flight_date' => '2015-05-19', 'from_city' => 'Napoli', 'to_city' => 'İstanbul', 'distance_km' => 1211],
            ['flight_date' => '2015-05-25', 'from_city' => 'İstanbul', 'to_city' => 'Roma', 'distance_km' => 1426],
            ['flight_date' => '2015-06-01', 'from_city' => 'Roma', 'to_city' => 'İstanbul', 'distance_km' => 1426],
            ['flight_date' => '2015-06-19', 'from_city' => 'Roma', 'to_city' => 'İstanbul', 'distance_km' => 1374],
            ['flight_date' => '2015-08-20', 'from_city' => 'İstanbul', 'to_city' => 'Venedik', 'distance_km' => 1403],
            ['flight_date' => '2015-08-23', 'from_city' => 'Bologna', 'to_city' => 'İstanbul', 'distance_km' => 1465],
            ['flight_date' => '2015-08-27', 'from_city' => 'İstanbul', 'to_city' => 'Napoli', 'distance_km' => 1211],
            ['flight_date' => '2015-08-30', 'from_city' => 'Napoli', 'to_city' => 'İstanbul', 'distance_km' => 1211],
            ['flight_date' => '2015-09-24', 'from_city' => 'İstanbul', 'to_city' => 'Lizbon', 'distance_km' => 3212],
            ['flight_date' => '2015-09-27', 'from_city' => 'Lizbon', 'to_city' => 'İstanbul', 'distance_km' => 3212],
            ['flight_date' => '2016-01-23', 'from_city' => 'İstanbul', 'to_city' => 'Miami', 'distance_km' => 9585],
            ['flight_date' => '2016-01-31', 'from_city' => 'Miami', 'to_city' => 'İstanbul', 'distance_km' => 9585],
            ['flight_date' => '2016-02-21', 'from_city' => 'İstanbul', 'to_city' => 'Nevşehir', 'distance_km' => 565],
            ['flight_date' => '2016-02-23', 'from_city' => 'Nevşehir', 'to_city' => 'İstanbul', 'distance_km' => 565],
            ['flight_date' => '2016-04-09', 'from_city' => 'İstanbul', 'to_city' => 'Nice', 'distance_km' => 1781],
            ['flight_date' => '2016-04-20', 'from_city' => 'Nice', 'to_city' => 'İstanbul', 'distance_km' => 1781],
            ['flight_date' => '2016-05-07', 'from_city' => 'İstanbul', 'to_city' => 'Lizbon', 'distance_km' => 3212],
            ['flight_date' => '2016-05-14', 'from_city' => 'Madrid', 'to_city' => 'İstanbul', 'distance_km' => 2703],
            ['flight_date' => '2016-05-19', 'from_city' => 'İstanbul', 'to_city' => 'Napoli', 'distance_km' => 1211],
            ['flight_date' => '2016-05-24', 'from_city' => 'İstanbul', 'to_city' => 'Atina', 'distance_km' => 554],
            ['flight_date' => '2016-06-03', 'from_city' => 'Barselona', 'to_city' => 'İstanbul', 'distance_km' => 2273],
            ['flight_date' => '2016-06-10', 'from_city' => 'İstanbul', 'to_city' => 'Milano', 'distance_km' => 1682],
            ['flight_date' => '2016-06-21', 'from_city' => 'Nice', 'to_city' => 'İstanbul', 'distance_km' => 1781],
            ['flight_date' => '2016-06-25', 'from_city' => 'İstanbul', 'to_city' => 'Cenova', 'distance_km' => 1656],
            ['flight_date' => '2016-07-02', 'from_city' => 'Cenova', 'to_city' => 'İstanbul', 'distance_km' => 1656],
            ['flight_date' => '2016-07-06', 'from_city' => 'İstanbul', 'to_city' => 'Amsterdam', 'distance_km' => 2184],
            ['flight_date' => '2016-07-15', 'from_city' => 'Amsterdam', 'to_city' => 'İstanbul', 'distance_km' => 2184],
            ['flight_date' => '2016-08-06', 'from_city' => 'İstanbul', 'to_city' => 'Stockholm', 'distance_km' => 2176],
            ['flight_date' => '2016-08-13', 'from_city' => 'Stockholm', 'to_city' => 'İstanbul', 'distance_km' => 2176],
            ['flight_date' => '2016-08-26', 'from_city' => 'İstanbul', 'to_city' => 'Napoli', 'distance_km' => 1211],
            ['flight_date' => '2016-08-30', 'from_city' => 'Napoli', 'to_city' => 'İstanbul', 'distance_km' => 1211],
            ['flight_date' => '2016-09-12', 'from_city' => 'İstanbul', 'to_city' => 'Torino', 'distance_km' => 1759],
            ['flight_date' => '2016-09-23', 'from_city' => 'Torino', 'to_city' => 'İstanbul', 'distance_km' => 1759],
            ['flight_date' => '2016-10-12', 'from_city' => 'İstanbul', 'to_city' => 'Catania', 'distance_km' => 1249],
            ['flight_date' => '2016-10-16', 'from_city' => 'Catania', 'to_city' => 'İstanbul', 'distance_km' => 1249],
            ['flight_date' => '2017-01-20', 'from_city' => 'İstanbul', 'to_city' => 'Miami', 'distance_km' => 9585],
            ['flight_date' => '2017-01-28', 'from_city' => 'Miami', 'to_city' => 'İstanbul', 'distance_km' => 9585],
            ['flight_date' => '2017-04-20', 'from_city' => 'İstanbul', 'to_city' => 'Napoli', 'distance_km' => 1211],
            ['flight_date' => '2017-04-23', 'from_city' => 'Napoli', 'to_city' => 'İstanbul', 'distance_km' => 1211],
            ['flight_date' => '2017-04-29', 'from_city' => 'İstanbul', 'to_city' => 'Milano', 'distance_km' => 1682],
            ['flight_date' => '2017-05-06', 'from_city' => 'Milano', 'to_city' => 'İstanbul', 'distance_km' => 1682],
            ['flight_date' => '2017-05-09', 'from_city' => 'İstanbul', 'to_city' => 'Delhi', 'distance_km' => 4565],
            ['flight_date' => '2017-05-20', 'from_city' => 'Katmandu', 'to_city' => 'İstanbul', 'distance_km' => 5305],
            ['flight_date' => '2017-06-01', 'from_city' => 'İstanbul', 'to_city' => 'Hamburg', 'distance_km' => 1958],
            ['flight_date' => '2017-06-12', 'from_city' => 'Hamburg', 'to_city' => 'İstanbul', 'distance_km' => 1958],
            ['flight_date' => '2017-07-02', 'from_city' => 'İstanbul', 'to_city' => 'Amsterdam', 'distance_km' => 2184],
            ['flight_date' => '2017-07-11', 'from_city' => 'Amsterdam', 'to_city' => 'İstanbul', 'distance_km' => 2184],
            ['flight_date' => '2017-07-14', 'from_city' => 'İstanbul', 'to_city' => 'Roma', 'distance_km' => 1426],
            ['flight_date' => '2017-07-17', 'from_city' => 'Roma', 'to_city' => 'İstanbul', 'distance_km' => 1426],
            ['flight_date' => '2017-07-24', 'from_city' => 'İstanbul', 'to_city' => 'Londra', 'distance_km' => 2461],
            ['flight_date' => '2017-08-05', 'from_city' => 'Londra', 'to_city' => 'İstanbul', 'distance_km' => 2488],
            ['flight_date' => '2017-08-28', 'from_city' => 'İstanbul', 'to_city' => 'Nice', 'distance_km' => 1781],
            ['flight_date' => '2017-08-31', 'from_city' => 'Nice', 'to_city' => 'İstanbul', 'distance_km' => 1781],
            ['flight_date' => '2017-09-01', 'from_city' => 'İstanbul', 'to_city' => 'Londra', 'distance_km' => 2461],
            ['flight_date' => '2017-09-04', 'from_city' => 'Londra', 'to_city' => 'İstanbul', 'distance_km' => 2461],
            ['flight_date' => '2017-09-20', 'from_city' => 'İstanbul', 'to_city' => 'Roma', 'distance_km' => 1374],
            ['flight_date' => '2017-09-24', 'from_city' => 'Venedik', 'to_city' => 'İstanbul', 'distance_km' => 1403],
            ['flight_date' => '2017-09-26', 'from_city' => 'İstanbul', 'to_city' => 'Delhi', 'distance_km' => 4565],
            ['flight_date' => '2017-10-01', 'from_city' => 'Delhi', 'to_city' => 'Varanasi', 'distance_km' => 667],
            ['flight_date' => '2017-10-02', 'from_city' => 'Varanasi', 'to_city' => 'Delhi', 'distance_km' => 667],
            ['flight_date' => '2017-10-07', 'from_city' => 'Katmandu', 'to_city' => 'İstanbul', 'distance_km' => 5305],
            ['flight_date' => '2017-10-22', 'from_city' => 'İstanbul', 'to_city' => 'Delhi', 'distance_km' => 4565],
            ['flight_date' => '2017-11-02', 'from_city' => 'Katmandu', 'to_city' => 'İstanbul', 'distance_km' => 5305],
            ['flight_date' => '2017-11-04', 'from_city' => 'İstanbul', 'to_city' => 'Milano', 'distance_km' => 1682],
            ['flight_date' => '2017-11-14', 'from_city' => 'Nice', 'to_city' => 'İstanbul', 'distance_km' => 1781],
            ['flight_date' => '2017-11-21', 'from_city' => 'İstanbul', 'to_city' => 'Delhi', 'distance_km' => 4565],
            ['flight_date' => '2017-12-02', 'from_city' => 'Katmandu', 'to_city' => 'İstanbul', 'distance_km' => 5305],
            ['flight_date' => '2018-01-13', 'from_city' => 'Male', 'to_city' => 'Male', 'distance_km' => 0],
            ['flight_date' => '2018-01-27', 'from_city' => 'Male', 'to_city' => 'Male', 'distance_km' => 0],
            ['flight_date' => '2018-01-28', 'from_city' => 'İstanbul', 'to_city' => 'Bangkok', 'distance_km' => 7512],
            ['flight_date' => '2018-02-03', 'from_city' => 'Bangkok', 'to_city' => 'İstanbul', 'distance_km' => 7512],
            ['flight_date' => '2018-02-17', 'from_city' => 'İstanbul', 'to_city' => 'Delhi', 'distance_km' => 4565],
            ['flight_date' => '2018-02-28', 'from_city' => 'Katmandu', 'to_city' => 'İstanbul', 'distance_km' => 5305],
            ['flight_date' => '2018-03-17', 'from_city' => 'İstanbul', 'to_city' => 'Bologna', 'distance_km' => 1465],
            ['flight_date' => '2018-03-21', 'from_city' => 'Bologna', 'to_city' => 'İstanbul', 'distance_km' => 1465],
            ['flight_date' => '2018-03-24', 'from_city' => 'İstanbul', 'to_city' => 'Delhi', 'distance_km' => 4565],
            ['flight_date' => '2018-04-04', 'from_city' => 'Katmandu', 'to_city' => 'İstanbul', 'distance_km' => 5305],
            ['flight_date' => '2018-04-21', 'from_city' => 'İstanbul', 'to_city' => 'Delhi', 'distance_km' => 4565],
            ['flight_date' => '2018-05-02', 'from_city' => 'Katmandu', 'to_city' => 'İstanbul', 'distance_km' => 5305],
            ['flight_date' => '2018-05-04', 'from_city' => 'İstanbul', 'to_city' => 'Roma', 'distance_km' => 1374],
            ['flight_date' => '2018-05-11', 'from_city' => 'Roma', 'to_city' => 'İstanbul', 'distance_km' => 1374],
            ['flight_date' => '2018-05-12', 'from_city' => 'İstanbul', 'to_city' => 'Hamburg', 'distance_km' => 1958],
            ['flight_date' => '2018-05-19', 'from_city' => 'Hamburg', 'to_city' => 'İstanbul', 'distance_km' => 1958],
            ['flight_date' => '2018-05-24', 'from_city' => 'İstanbul', 'to_city' => 'Oslo', 'distance_km' => 2426],
            ['flight_date' => '2018-06-02', 'from_city' => 'Berlin', 'to_city' => 'İstanbul', 'distance_km' => 1712],
            ['flight_date' => '2018-06-09', 'from_city' => 'İstanbul', 'to_city' => 'Milano', 'distance_km' => 1682],
            ['flight_date' => '2018-06-16', 'from_city' => 'Milano', 'to_city' => 'İstanbul', 'distance_km' => 1682],
            ['flight_date' => '2018-06-30', 'from_city' => 'İstanbul', 'to_city' => 'Hamburg', 'distance_km' => 1958],
            ['flight_date' => '2018-07-07', 'from_city' => 'Hamburg', 'to_city' => 'İstanbul', 'distance_km' => 1958],
            ['flight_date' => '2018-10-17', 'from_city' => 'İstanbul', 'to_city' => 'Milano', 'distance_km' => 1682],
            ['flight_date' => '2018-10-26', 'from_city' => 'Milano', 'to_city' => 'İstanbul', 'distance_km' => 1682],
            ['flight_date' => '2018-11-30', 'from_city' => 'İstanbul', 'to_city' => 'Nice', 'distance_km' => 1781],
            ['flight_date' => '2018-12-18', 'from_city' => 'Miami', 'to_city' => 'İstanbul', 'distance_km' => 9585],
            ['flight_date' => '2019-01-14', 'from_city' => 'İstanbul', 'to_city' => 'Singapur', 'distance_km' => 8678],
            ['flight_date' => '2019-01-29', 'from_city' => 'Singapur', 'to_city' => 'İstanbul', 'distance_km' => 8678],
            ['flight_date' => '2019-02-10', 'from_city' => 'İstanbul', 'to_city' => 'Miami', 'distance_km' => 9585],
            ['flight_date' => '2019-02-18', 'from_city' => 'Miami', 'to_city' => 'İstanbul', 'distance_km' => 9585],
            ['flight_date' => '2019-04-20', 'from_city' => 'İstanbul', 'to_city' => 'Delhi', 'distance_km' => 4565],
            ['flight_date' => '2019-04-28', 'from_city' => 'Delhi', 'to_city' => 'Katmandu', 'distance_km' => 815],
            ['flight_date' => '2019-05-01', 'from_city' => 'Katmandu', 'to_city' => 'İstanbul', 'distance_km' => 5305],
            ['flight_date' => '2019-05-17', 'from_city' => 'İstanbul', 'to_city' => 'Milano', 'distance_km' => 1682],
            ['flight_date' => '2019-05-24', 'from_city' => 'Milano', 'to_city' => 'İstanbul', 'distance_km' => 1682],
            ['flight_date' => '2019-06-02', 'from_city' => 'İstanbul', 'to_city' => 'Miami', 'distance_km' => 9585],
            ['flight_date' => '2019-06-10', 'from_city' => 'Miami', 'to_city' => 'İstanbul', 'distance_km' => 9585],
            ['flight_date' => '2019-07-06', 'from_city' => 'İstanbul', 'to_city' => 'Stockholm', 'distance_km' => 2176],
            ['flight_date' => '2019-07-13', 'from_city' => 'Stockholm', 'to_city' => 'İstanbul', 'distance_km' => 2176],
            ['flight_date' => '2019-07-30', 'from_city' => 'İstanbul', 'to_city' => 'Hamburg', 'distance_km' => 1958],
            ['flight_date' => '2019-08-09', 'from_city' => 'Hamburg', 'to_city' => 'İstanbul', 'distance_km' => 1958],
            ['flight_date' => '2019-08-10', 'from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'distance_km' => 1978],
            ['flight_date' => '2019-08-24', 'from_city' => 'Kopenhag', 'to_city' => 'İstanbul', 'distance_km' => 1978],
            ['flight_date' => '2019-08-30', 'from_city' => 'İstanbul', 'to_city' => 'Hamburg', 'distance_km' => 1958],
            ['flight_date' => '2019-09-10', 'from_city' => 'Hamburg', 'to_city' => 'İstanbul', 'distance_km' => 1958],
            ['flight_date' => '2019-09-18', 'from_city' => 'İstanbul', 'to_city' => 'Londra', 'distance_km' => 2461],
            ['flight_date' => '2019-09-27', 'from_city' => 'Londra', 'to_city' => 'İstanbul', 'distance_km' => 2461],
            ['flight_date' => '2019-10-05', 'from_city' => 'İstanbul', 'to_city' => 'Marsilya', 'distance_km' => 1942],
            ['flight_date' => '2019-10-13', 'from_city' => 'Marsilya', 'to_city' => 'İstanbul', 'distance_km' => 1942],
            ['flight_date' => '2019-11-01', 'from_city' => 'İstanbul', 'to_city' => 'Miami', 'distance_km' => 9585],
            ['flight_date' => '2019-11-09', 'from_city' => 'Miami', 'to_city' => 'İstanbul', 'distance_km' => 9585],
            ['flight_date' => '2020-01-11', 'from_city' => 'İstanbul', 'to_city' => 'Male', 'distance_km' => 6063],
            ['flight_date' => '2020-01-18', 'from_city' => 'Mumbai', 'to_city' => 'İstanbul', 'distance_km' => 4834],
            ['flight_date' => '2020-02-04', 'from_city' => 'Singapur', 'to_city' => 'İstanbul', 'distance_km' => 8678],
            ['flight_date' => '2022-01-28', 'from_city' => 'İstanbul', 'to_city' => 'Miami', 'distance_km' => 9585],
            ['flight_date' => '2022-02-05', 'from_city' => 'Miami', 'to_city' => 'İstanbul', 'distance_km' => 9585],
            ['flight_date' => '2022-04-13', 'from_city' => 'İstanbul', 'to_city' => 'Cancun', 'distance_km' => 10432],
            ['flight_date' => '2022-04-22', 'from_city' => 'Mexico City', 'to_city' => 'İstanbul', 'distance_km' => 11389],
            ['flight_date' => '2022-05-13', 'from_city' => 'İstanbul', 'to_city' => 'Cancun', 'distance_km' => 10432],
            ['flight_date' => '2022-05-16', 'from_city' => 'Cancun', 'to_city' => 'İstanbul', 'distance_km' => 10432],
            ['flight_date' => '2022-05-31', 'from_city' => 'İstanbul', 'to_city' => 'Cancun', 'distance_km' => 10432],
            ['flight_date' => '2022-06-05', 'from_city' => 'Cancun', 'to_city' => 'İstanbul', 'distance_km' => 10432],
            ['flight_date' => '2022-06-08', 'from_city' => 'İstanbul', 'to_city' => 'Havana', 'distance_km' => 9957],
            ['flight_date' => '2022-06-13', 'from_city' => 'Havana', 'to_city' => 'İstanbul', 'distance_km' => 9957],
            ['flight_date' => '2022-06-15', 'from_city' => 'İstanbul', 'to_city' => 'Havana', 'distance_km' => 9957],
            ['flight_date' => '2022-06-22', 'from_city' => 'Cancun', 'to_city' => 'İstanbul', 'distance_km' => 10432],
            ['flight_date' => '2022-07-17', 'from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'distance_km' => 1978],
            ['flight_date' => '2022-07-24', 'from_city' => 'Kopenhag', 'to_city' => 'İstanbul', 'distance_km' => 1978],
            ['flight_date' => '2022-07-31', 'from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'distance_km' => 1978],
            ['flight_date' => '2022-08-07', 'from_city' => 'Kopenhag', 'to_city' => 'İstanbul', 'distance_km' => 1978],
            ['flight_date' => '2022-08-08', 'from_city' => 'İstanbul', 'to_city' => 'Havana', 'distance_km' => 9957],
            ['flight_date' => '2022-08-14', 'from_city' => 'Cancun', 'to_city' => 'İstanbul', 'distance_km' => 10432],
            ['flight_date' => '2022-10-03', 'from_city' => 'Antalya', 'to_city' => 'İstanbul', 'distance_km' => 518],
            ['flight_date' => '2022-10-04', 'from_city' => 'İstanbul', 'to_city' => 'Vilnius', 'distance_km' => 1507],
            ['flight_date' => '2022-10-11', 'from_city' => 'Helsinki', 'to_city' => 'İstanbul', 'distance_km' => 2133],
            ['flight_date' => '2022-10-28', 'from_city' => 'İstanbul', 'to_city' => 'Milano', 'distance_km' => 1682],
            ['flight_date' => '2022-11-11', 'from_city' => 'İstanbul', 'to_city' => 'Antalya', 'distance_km' => 518],
            ['flight_date' => '2022-11-11', 'from_city' => 'Milano', 'to_city' => 'İstanbul', 'distance_km' => 1682],
            ['flight_date' => '2022-11-19', 'from_city' => 'Antalya', 'to_city' => 'İstanbul', 'distance_km' => 518],
            ['flight_date' => '2022-11-19', 'from_city' => 'İstanbul', 'to_city' => 'Milano', 'distance_km' => 1682],
            ['flight_date' => '2022-12-11', 'from_city' => 'Buenos Aires', 'to_city' => 'İstanbul', 'distance_km' => 12269],
            ['flight_date' => '2023-03-17', 'from_city' => 'İstanbul', 'to_city' => 'Catania', 'distance_km' => 1249],
            ['flight_date' => '2023-03-21', 'from_city' => 'Malta', 'to_city' => 'İstanbul', 'distance_km' => 1377],
            ['flight_date' => '2023-04-08', 'from_city' => 'Antalya', 'to_city' => 'İstanbul', 'distance_km' => 518],
            ['flight_date' => '2023-04-08', 'from_city' => 'İstanbul', 'to_city' => 'Marsilya', 'distance_km' => 1942],
            ['flight_date' => '2023-04-22', 'from_city' => 'Marsilya', 'to_city' => 'İstanbul', 'distance_km' => 1942],
            ['flight_date' => '2023-04-23', 'from_city' => 'İstanbul', 'to_city' => 'Gazipaşa', 'distance_km' => 633],
            ['flight_date' => '2023-05-05', 'from_city' => 'Antalya', 'to_city' => 'İstanbul', 'distance_km' => 518],
            ['flight_date' => '2023-05-05', 'from_city' => 'İstanbul', 'to_city' => 'Milano', 'distance_km' => 1682],
            ['flight_date' => '2023-05-20', 'from_city' => 'İstanbul', 'to_city' => 'Antalya', 'distance_km' => 518],
            ['flight_date' => '2023-05-20', 'from_city' => 'Kopenhag', 'to_city' => 'İstanbul', 'distance_km' => 1978],
            ['flight_date' => '2023-06-01', 'from_city' => 'Antalya', 'to_city' => 'İstanbul', 'distance_km' => 463],
            ['flight_date' => '2023-06-03', 'from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'distance_km' => 1978],
            ['flight_date' => '2023-06-10', 'from_city' => 'Kopenhag', 'to_city' => 'İstanbul', 'distance_km' => 1978],
            ['flight_date' => '2023-06-10', 'from_city' => 'İstanbul', 'to_city' => 'Antalya', 'distance_km' => 518],
            ['flight_date' => '2023-06-24', 'from_city' => 'Antalya', 'to_city' => 'İstanbul', 'distance_km' => 518],
            ['flight_date' => '2023-06-24', 'from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'distance_km' => 1978],
            ['flight_date' => '2023-07-01', 'from_city' => 'Kopenhag', 'to_city' => 'İstanbul', 'distance_km' => 1978],
            ['flight_date' => '2023-07-01', 'from_city' => 'İstanbul', 'to_city' => 'Antalya', 'distance_km' => 518],
            ['flight_date' => '2023-07-09', 'from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'distance_km' => 2038],
            ['flight_date' => '2023-07-16', 'from_city' => 'İstanbul', 'to_city' => 'Antalya', 'distance_km' => 463],
            ['flight_date' => '2023-07-16', 'from_city' => 'Kopenhag', 'to_city' => 'İstanbul', 'distance_km' => 2038],
            ['flight_date' => '2023-07-29', 'from_city' => 'Antalya', 'to_city' => 'İstanbul', 'distance_km' => 518],
            ['flight_date' => '2023-07-29', 'from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'distance_km' => 1978],
            ['flight_date' => '2023-08-05', 'from_city' => 'Kopenhag', 'to_city' => 'İstanbul', 'distance_km' => 1978],
            ['flight_date' => '2023-09-02', 'from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'distance_km' => 1978],
            ['flight_date' => '2023-09-02', 'from_city' => 'Gazipaşa', 'to_city' => 'İstanbul', 'distance_km' => 633],
            ['flight_date' => '2023-09-09', 'from_city' => 'Kopenhag', 'to_city' => 'İstanbul', 'distance_km' => 1978],
            ['flight_date' => '2023-09-09', 'from_city' => 'İstanbul', 'to_city' => 'Antalya', 'distance_km' => 518],
            ['flight_date' => '2023-09-19', 'from_city' => 'Antalya', 'to_city' => 'İstanbul', 'distance_km' => 463],
            ['flight_date' => '2023-10-31', 'from_city' => 'Gazipaşa', 'to_city' => 'İstanbul', 'distance_km' => 633],
            ['flight_date' => '2023-11-01', 'from_city' => 'İstanbul', 'to_city' => 'Marsilya', 'distance_km' => 1942],
            ['flight_date' => '2023-11-11', 'from_city' => 'Marsilya', 'to_city' => 'İstanbul', 'distance_km' => 1942],
            ['flight_date' => '2023-11-12', 'from_city' => 'İstanbul', 'to_city' => 'Antalya', 'distance_km' => 518],
            ['flight_date' => '2023-12-20', 'from_city' => 'İstanbul', 'to_city' => 'Tokyo', 'distance_km' => 8979],
            ['flight_date' => '2023-12-20', 'from_city' => 'Gazipaşa', 'to_city' => 'İstanbul', 'distance_km' => 633],
            ['flight_date' => '2024-01-02', 'from_city' => 'İstanbul', 'to_city' => 'Gazipaşa', 'distance_km' => 633],
            ['flight_date' => '2024-01-02', 'from_city' => 'Tokyo', 'to_city' => 'İstanbul', 'distance_km' => 8979],
            ['flight_date' => '2024-01-28', 'from_city' => 'İstanbul', 'to_city' => 'Rovaniemi', 'distance_km' => 2818],
            ['flight_date' => '2024-02-01', 'from_city' => 'Rovaniemi', 'to_city' => 'İstanbul', 'distance_km' => 2818],
            ['flight_date' => '2024-02-04', 'from_city' => 'İstanbul', 'to_city' => 'Rovaniemi', 'distance_km' => 2818],
            ['flight_date' => '2024-02-15', 'from_city' => 'Antalya', 'to_city' => 'İstanbul', 'distance_km' => 463],
            ['flight_date' => '2024-02-29', 'from_city' => 'Gazipaşa', 'to_city' => 'İstanbul', 'distance_km' => 633],
            ['flight_date' => '2024-03-01', 'from_city' => 'İstanbul', 'to_city' => 'Catania', 'distance_km' => 1249],
            ['flight_date' => '2024-03-05', 'from_city' => 'Malta', 'to_city' => 'İstanbul', 'distance_km' => 1377],
            ['flight_date' => '2024-03-06', 'from_city' => 'İstanbul', 'to_city' => 'Antalya', 'distance_km' => 518],
            ['flight_date' => '2024-05-18', 'from_city' => 'İstanbul', 'to_city' => 'Marsilya', 'distance_km' => 1942],
            ['flight_date' => '2024-05-25', 'from_city' => 'Marsilya', 'to_city' => 'İstanbul', 'distance_km' => 1942],
            ['flight_date' => '2024-05-26', 'from_city' => 'İstanbul', 'to_city' => 'Gazipaşa', 'distance_km' => 633],
            ['flight_date' => '2024-07-26', 'from_city' => 'İstanbul', 'to_city' => 'Londra', 'distance_km' => 2461],
            ['flight_date' => '2024-08-08', 'from_city' => 'Londra', 'to_city' => 'İstanbul', 'distance_km' => 2461],
            ['flight_date' => '2024-09-25', 'from_city' => 'Gazipaşa', 'to_city' => 'İstanbul', 'distance_km' => 633],
            ['flight_date' => '2024-09-26', 'from_city' => 'İstanbul', 'to_city' => 'Palermo', 'distance_km' => 1381],
            ['flight_date' => '2024-09-30', 'from_city' => 'Catania', 'to_city' => 'İstanbul', 'distance_km' => 1249],
            ['flight_date' => '2024-10-26', 'from_city' => 'İstanbul', 'to_city' => 'Malta', 'distance_km' => 1377],
            ['flight_date' => '2024-10-30', 'from_city' => 'Malta', 'to_city' => 'İstanbul', 'distance_km' => 1377],
            ['flight_date' => '2024-11-09', 'from_city' => 'İstanbul', 'to_city' => 'Torino', 'distance_km' => 1759],
            ['flight_date' => '2024-11-16', 'from_city' => 'Nice', 'to_city' => 'İstanbul', 'distance_km' => 1781],
            ['flight_date' => '2024-11-22', 'from_city' => 'İstanbul', 'to_city' => 'Barselona', 'distance_km' => 2220],
            ['flight_date' => '2024-11-22', 'from_city' => 'Antalya', 'to_city' => 'İstanbul', 'distance_km' => 518],
            ['flight_date' => '2024-11-29', 'from_city' => 'Barselona', 'to_city' => 'İstanbul', 'distance_km' => 2220],
            ['flight_date' => '2024-11-30', 'from_city' => 'İstanbul', 'to_city' => 'Gazipaşa', 'distance_km' => 633],
            ['flight_date' => '2024-12-06', 'from_city' => 'Gazipaşa', 'to_city' => 'İstanbul', 'distance_km' => 633],
            ['flight_date' => '2024-12-17', 'from_city' => 'İstanbul', 'to_city' => 'Gazipaşa', 'distance_km' => 633],
            ['flight_date' => '2025-01-19', 'from_city' => 'İstanbul', 'to_city' => 'Rovaniemi', 'distance_km' => 2818],
            ['flight_date' => '2025-01-23', 'from_city' => 'Rovaniemi', 'to_city' => 'İstanbul', 'distance_km' => 2818],
            ['flight_date' => '2025-02-25', 'from_city' => 'Gazipaşa', 'to_city' => 'İstanbul', 'distance_km' => 633],
            ['flight_date' => '2025-02-26', 'from_city' => 'İstanbul', 'to_city' => 'Sao Paulo', 'distance_km' => 10559],
            ['flight_date' => '2025-02-26', 'from_city' => 'İstanbul', 'to_city' => 'Buenos Aires', 'distance_km' => 12269],
            ['flight_date' => '2025-03-10', 'from_city' => 'Buenos Aires', 'to_city' => 'Sao Paulo', 'distance_km' => 1722],
            ['flight_date' => '2025-03-10', 'from_city' => 'Buenos Aires', 'to_city' => 'İstanbul', 'distance_km' => 12269],
            ['flight_date' => '2025-03-31', 'from_city' => 'İstanbul', 'to_city' => 'Tokyo', 'distance_km' => 8979],
            ['flight_date' => '2025-03-31', 'from_city' => 'Antalya', 'to_city' => 'İstanbul', 'distance_km' => 518],
            ['flight_date' => '2025-04-08', 'from_city' => 'Osaka', 'to_city' => 'İstanbul', 'distance_km' => 8744],
            ['flight_date' => '2025-05-03', 'from_city' => 'İstanbul', 'to_city' => 'Hamburg', 'distance_km' => 1958],
            ['flight_date' => '2025-05-10', 'from_city' => 'Hamburg', 'to_city' => 'İstanbul', 'distance_km' => 1958],
            ['flight_date' => '2025-05-11', 'from_city' => 'İstanbul', 'to_city' => 'Antalya', 'distance_km' => 518],
            ['flight_date' => '2025-05-15', 'from_city' => 'Gazipaşa', 'to_city' => 'İstanbul', 'distance_km' => 633],
            ['flight_date' => '2025-05-17', 'from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'distance_km' => 1978],
            ['flight_date' => '2025-05-24', 'from_city' => 'Kopenhag', 'to_city' => 'İstanbul', 'distance_km' => 1978],
            ['flight_date' => '2025-06-02', 'from_city' => 'İstanbul', 'to_city' => 'St. Petersburg', 'distance_km' => 2063],
            ['flight_date' => '2025-06-10', 'from_city' => 'Moskova', 'to_city' => 'İstanbul', 'distance_km' => 1708],
            ['flight_date' => '2025-07-02', 'from_city' => 'İstanbul', 'to_city' => 'Londra', 'distance_km' => 2488],
            ['flight_date' => '2025-07-17', 'from_city' => 'Londra', 'to_city' => 'İstanbul', 'distance_km' => 2488],
            ['flight_date' => '2025-08-04', 'from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'distance_km' => 1978],
            ['flight_date' => '2025-08-04', 'from_city' => 'Antalya', 'to_city' => 'İstanbul', 'distance_km' => 518],
            ['flight_date' => '2025-08-11', 'from_city' => 'İstanbul', 'to_city' => 'Antalya', 'distance_km' => 518],
            ['flight_date' => '2025-08-11', 'from_city' => 'Stockholm', 'to_city' => 'İstanbul', 'distance_km' => 2176],
            ['flight_date' => '2025-08-21', 'from_city' => 'Antalya', 'to_city' => 'İstanbul', 'distance_km' => 463],
            ['flight_date' => '2025-09-11', 'from_city' => 'Antalya', 'to_city' => 'İstanbul', 'distance_km' => 463],
            ['flight_date' => '2025-09-18', 'from_city' => 'İstanbul', 'to_city' => 'Antalya', 'distance_km' => 463],
            ['flight_date' => '2025-10-23', 'from_city' => 'İstanbul', 'to_city' => 'Roma', 'distance_km' => 1426],
            ['flight_date' => '2025-10-23', 'from_city' => 'Antalya', 'to_city' => 'İstanbul', 'distance_km' => 463],
            ['flight_date' => '2025-10-30', 'from_city' => 'İstanbul', 'to_city' => 'Gazipaşa', 'distance_km' => 633],
            ['flight_date' => '2025-11-21', 'from_city' => 'Gazipaşa', 'to_city' => 'İstanbul', 'distance_km' => 633],
            ['flight_date' => '2025-11-24', 'from_city' => 'İstanbul', 'to_city' => 'Tokyo', 'distance_km' => 8979],
            ['flight_date' => '2025-12-02', 'from_city' => 'Osaka', 'to_city' => 'İstanbul', 'distance_km' => 8744],
            ['flight_date' => '2025-12-26', 'from_city' => 'Antalya', 'to_city' => 'İstanbul', 'distance_km' => 518],
            ['flight_date' => '2026-03-12', 'from_city' => 'İstanbul', 'to_city' => 'Hanoi', 'distance_km' => 7415],
            ['flight_date' => '2026-03-22', 'from_city' => 'Ho Chi Minh', 'to_city' => 'İstanbul', 'distance_km' => 8209],
            ['flight_date' => '2026-04-04', 'from_city' => 'İstanbul', 'to_city' => 'Cape Town', 'distance_km' => 8431],
            ['flight_date' => '2026-04-16', 'from_city' => 'Johannesburg', 'to_city' => 'İstanbul', 'distance_km' => 7496],
            ['flight_date' => '2026-06-01', 'from_city' => 'İstanbul', 'to_city' => 'Edinburgh', 'distance_km' => 2830],
            ['flight_date' => '2026-06-07', 'from_city' => 'Londra', 'to_city' => 'İstanbul', 'distance_km' => 2488],
        ];

        foreach ($updates as $u) {
            Flight::where('flight_date', $u['flight_date'])
                ->where('from_city', $u['from_city'])
                ->where('to_city', $u['to_city'])
                ->update(['distance_km' => $u['distance_km']]);
        }
    }
}
