<?php

namespace Database\Seeders;

use App\Models\Flight;
use Illuminate\Database\Seeder;

/**
 * Miles&Smiles mil durumu tablosundan (earningMileStatement.pdf) çıkarılan
 * gerçek uçuş kayıtları. Sadece "Uçuş" satırları alındı; Program Ortakları,
 * Kampanya Kazanımı, İşlem Düzeltme ve You&Friends gibi mil-kaynaklı ama
 * uçuş olmayan kayıtlar hariç tutuldu. Her uçuş PDF'te iki satır halinde
 * (temel mil + statü bonus mili) göründüğü için tarih+rota bazında
 * tekilleştirildi. Eskiden yeniye kronolojik sırayla eklenir.
 *
 * Notlar:
 * - PDF'te uçuş numarası ve mesafe (km) bilgisi yok, bu yüzden boş bırakıldı.
 * - Havayolu tüm kayıtlar için "Turkish Airlines" varsayıldı (Miles&Smiles
 *   istatement'i olduğu için); kod paylaşımlı (codeshare) uçuşlar farklı
 *   olabilir, gerekirse admin panelden düzeltilebilir.
 * - 22.05.2016 tarihli "TEQ-TEQ" satırı PDF'te bu şekilde geçiyor, IATA kodu
 *   net çözülemedi; "Bilinmiyor (TEQ)" olarak işaretlendi, admin panelden
 *   düzeltilebilir.
 */
class FlightHistoryImportSeeder extends Seeder
{
    public function run(): void
    {
        $flights = [
            ['from_city' => 'Antalya', 'to_city' => 'İstanbul', 'flight_date' => '2003-11-04', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (Y)', 'notes_en' => 'Economy class (Y)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'flight_date' => '2003-11-19', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (N)', 'notes_en' => 'Economy class (N)'],
            ['from_city' => 'Ankara', 'to_city' => 'İstanbul', 'flight_date' => '2004-01-17', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (N)', 'notes_en' => 'Economy class (N)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'flight_date' => '2004-01-17', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (N)', 'notes_en' => 'Economy class (N)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Singapur', 'flight_date' => '2012-08-21', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (W)', 'notes_en' => 'Economy class (W)'],
            ['from_city' => 'Singapur', 'to_city' => 'İstanbul', 'flight_date' => '2012-08-27', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (W)', 'notes_en' => 'Economy class (W)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Ankara', 'flight_date' => '2012-09-16', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (Q)', 'notes_en' => 'Economy class (Q)'],
            ['from_city' => 'Kayseri', 'to_city' => 'İstanbul', 'flight_date' => '2012-09-18', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (C)', 'notes_en' => 'Economy class (C)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Cenova', 'flight_date' => '2013-07-01', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (W)', 'notes_en' => 'Economy class (W)'],
            ['from_city' => 'Cenova', 'to_city' => 'İstanbul', 'flight_date' => '2013-07-08', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (W)', 'notes_en' => 'Economy class (W)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Cenova', 'flight_date' => '2014-01-30', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (W)', 'notes_en' => 'Economy class (W)'],
            ['from_city' => 'Cenova', 'to_city' => 'İstanbul', 'flight_date' => '2014-02-10', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (W)', 'notes_en' => 'Economy class (W)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Cenova', 'flight_date' => '2014-10-19', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (P)', 'notes_en' => 'Economy class (P)'],
            ['from_city' => 'Cenova', 'to_city' => 'İstanbul', 'flight_date' => '2014-10-26', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (P)', 'notes_en' => 'Economy class (P)'],
            ['from_city' => 'Sao Paulo', 'to_city' => 'İstanbul', 'flight_date' => '2014-11-28', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Napoli', 'flight_date' => '2015-05-16', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Napoli', 'to_city' => 'İstanbul', 'flight_date' => '2015-05-19', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Roma', 'flight_date' => '2015-05-25', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (B)', 'notes_en' => 'Economy class (B)'],
            ['from_city' => 'Roma', 'to_city' => 'İstanbul', 'flight_date' => '2015-06-01', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (T)', 'notes_en' => 'Economy class (T)'],
            ['from_city' => 'Roma', 'to_city' => 'İstanbul', 'flight_date' => '2015-06-19', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (V)', 'notes_en' => 'Economy class (V)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Venedik', 'flight_date' => '2015-08-20', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Bologna', 'to_city' => 'İstanbul', 'flight_date' => '2015-08-23', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Napoli', 'flight_date' => '2015-08-27', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Napoli', 'to_city' => 'İstanbul', 'flight_date' => '2015-08-30', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Lizbon', 'flight_date' => '2015-09-24', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Lizbon', 'to_city' => 'İstanbul', 'flight_date' => '2015-09-27', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Miami', 'flight_date' => '2016-01-23', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (W)', 'notes_en' => 'Economy class (W)'],
            ['from_city' => 'Miami', 'to_city' => 'İstanbul', 'flight_date' => '2016-01-31', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (W)', 'notes_en' => 'Economy class (W)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Nevşehir', 'flight_date' => '2016-02-21', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (P)', 'notes_en' => 'Economy class (P)'],
            ['from_city' => 'Nevşehir', 'to_city' => 'İstanbul', 'flight_date' => '2016-02-23', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (W)', 'notes_en' => 'Economy class (W)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Nice', 'flight_date' => '2016-04-09', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Nice', 'to_city' => 'İstanbul', 'flight_date' => '2016-04-20', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Lizbon', 'flight_date' => '2016-05-07', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (V)', 'notes_en' => 'Economy class (V)'],
            ['from_city' => 'Madrid', 'to_city' => 'İstanbul', 'flight_date' => '2016-05-14', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (P)', 'notes_en' => 'Economy class (P)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Napoli', 'flight_date' => '2016-05-19', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Bilinmiyor (TEQ)', 'to_city' => 'Bilinmiyor (TEQ)', 'flight_date' => '2016-05-22', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Atina', 'flight_date' => '2016-05-24', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (M)', 'notes_en' => 'Economy class (M)'],
            ['from_city' => 'Barselona', 'to_city' => 'İstanbul', 'flight_date' => '2016-06-03', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (P)', 'notes_en' => 'Economy class (P)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Milano', 'flight_date' => '2016-06-10', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Nice', 'to_city' => 'İstanbul', 'flight_date' => '2016-06-21', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Cenova', 'flight_date' => '2016-06-25', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (V)', 'notes_en' => 'Economy class (V)'],
            ['from_city' => 'Cenova', 'to_city' => 'İstanbul', 'flight_date' => '2016-07-02', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (P)', 'notes_en' => 'Economy class (P)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Amsterdam', 'flight_date' => '2016-07-06', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Amsterdam', 'to_city' => 'İstanbul', 'flight_date' => '2016-07-15', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Stockholm', 'flight_date' => '2016-08-06', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'Stockholm', 'to_city' => 'İstanbul', 'flight_date' => '2016-08-13', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Napoli', 'flight_date' => '2016-08-26', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Napoli', 'to_city' => 'İstanbul', 'flight_date' => '2016-08-30', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Torino', 'flight_date' => '2016-09-12', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Torino', 'to_city' => 'İstanbul', 'flight_date' => '2016-09-23', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Catania', 'flight_date' => '2016-10-12', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Catania', 'to_city' => 'İstanbul', 'flight_date' => '2016-10-16', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Miami', 'flight_date' => '2017-01-20', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Miami', 'to_city' => 'İstanbul', 'flight_date' => '2017-01-28', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Napoli', 'flight_date' => '2017-04-20', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Napoli', 'to_city' => 'İstanbul', 'flight_date' => '2017-04-23', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Milano', 'flight_date' => '2017-04-29', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (W)', 'notes_en' => 'Economy class (W)'],
            ['from_city' => 'Milano', 'to_city' => 'İstanbul', 'flight_date' => '2017-05-06', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (W)', 'notes_en' => 'Economy class (W)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Delhi', 'flight_date' => '2017-05-09', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'Katmandu', 'to_city' => 'İstanbul', 'flight_date' => '2017-05-20', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Hamburg', 'flight_date' => '2017-06-01', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (P)', 'notes_en' => 'Economy class (P)'],
            ['from_city' => 'Hamburg', 'to_city' => 'İstanbul', 'flight_date' => '2017-06-12', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (P)', 'notes_en' => 'Economy class (P)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Amsterdam', 'flight_date' => '2017-07-02', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Amsterdam', 'to_city' => 'İstanbul', 'flight_date' => '2017-07-11', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Roma', 'flight_date' => '2017-07-14', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Roma', 'to_city' => 'İstanbul', 'flight_date' => '2017-07-17', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Londra', 'flight_date' => '2017-07-24', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (P)', 'notes_en' => 'Economy class (P)'],
            ['from_city' => 'Londra', 'to_city' => 'İstanbul', 'flight_date' => '2017-08-05', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Nice', 'flight_date' => '2017-08-28', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Nice', 'to_city' => 'İstanbul', 'flight_date' => '2017-08-31', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Londra', 'flight_date' => '2017-09-01', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Londra', 'to_city' => 'İstanbul', 'flight_date' => '2017-09-04', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Roma', 'flight_date' => '2017-09-20', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Venedik', 'to_city' => 'İstanbul', 'flight_date' => '2017-09-24', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Delhi', 'flight_date' => '2017-09-26', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'Delhi', 'to_city' => 'Varanasi', 'flight_date' => '2017-10-01', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (H)', 'notes_en' => 'Economy class (H)'],
            ['from_city' => 'Varanasi', 'to_city' => 'Delhi', 'flight_date' => '2017-10-02', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (V)', 'notes_en' => 'Economy class (V)'],
            ['from_city' => 'Katmandu', 'to_city' => 'İstanbul', 'flight_date' => '2017-10-07', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Delhi', 'flight_date' => '2017-10-22', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'Katmandu', 'to_city' => 'İstanbul', 'flight_date' => '2017-11-02', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Milano', 'flight_date' => '2017-11-04', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Nice', 'to_city' => 'İstanbul', 'flight_date' => '2017-11-14', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Delhi', 'flight_date' => '2017-11-21', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'Katmandu', 'to_city' => 'İstanbul', 'flight_date' => '2017-12-02', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (T)', 'notes_en' => 'Economy class (T)'],
            ['from_city' => 'Male', 'to_city' => 'Male', 'flight_date' => '2018-01-13', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Male', 'to_city' => 'Male', 'flight_date' => '2018-01-27', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Bangkok', 'flight_date' => '2018-01-28', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Bangkok', 'to_city' => 'İstanbul', 'flight_date' => '2018-02-03', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Delhi', 'flight_date' => '2018-02-17', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Katmandu', 'to_city' => 'İstanbul', 'flight_date' => '2018-02-28', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Bologna', 'flight_date' => '2018-03-17', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Bologna', 'to_city' => 'İstanbul', 'flight_date' => '2018-03-21', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Delhi', 'flight_date' => '2018-03-24', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (Q)', 'notes_en' => 'Economy class (Q)'],
            ['from_city' => 'Katmandu', 'to_city' => 'İstanbul', 'flight_date' => '2018-04-04', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (Q)', 'notes_en' => 'Economy class (Q)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Delhi', 'flight_date' => '2018-04-21', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Katmandu', 'to_city' => 'İstanbul', 'flight_date' => '2018-05-02', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Roma', 'flight_date' => '2018-05-04', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Roma', 'to_city' => 'İstanbul', 'flight_date' => '2018-05-11', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Hamburg', 'flight_date' => '2018-05-12', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Hamburg', 'to_city' => 'İstanbul', 'flight_date' => '2018-05-19', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Oslo', 'flight_date' => '2018-05-24', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (W)', 'notes_en' => 'Economy class (W)'],
            ['from_city' => 'Berlin', 'to_city' => 'İstanbul', 'flight_date' => '2018-06-02', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Milano', 'flight_date' => '2018-06-09', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Milano', 'to_city' => 'İstanbul', 'flight_date' => '2018-06-16', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Hamburg', 'flight_date' => '2018-06-30', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Hamburg', 'to_city' => 'İstanbul', 'flight_date' => '2018-07-07', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Milano', 'flight_date' => '2018-10-17', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Milano', 'to_city' => 'İstanbul', 'flight_date' => '2018-10-26', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Nice', 'flight_date' => '2018-11-30', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Miami', 'to_city' => 'İstanbul', 'flight_date' => '2018-12-18', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Singapur', 'flight_date' => '2019-01-14', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Singapur', 'to_city' => 'İstanbul', 'flight_date' => '2019-01-29', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Miami', 'flight_date' => '2019-02-10', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (W)', 'notes_en' => 'Economy class (W)'],
            ['from_city' => 'Miami', 'to_city' => 'İstanbul', 'flight_date' => '2019-02-18', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (W)', 'notes_en' => 'Economy class (W)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Delhi', 'flight_date' => '2019-04-20', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Delhi', 'to_city' => 'Katmandu', 'flight_date' => '2019-04-28', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Katmandu', 'to_city' => 'İstanbul', 'flight_date' => '2019-05-01', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Milano', 'flight_date' => '2019-05-17', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (W)', 'notes_en' => 'Economy class (W)'],
            ['from_city' => 'Milano', 'to_city' => 'İstanbul', 'flight_date' => '2019-05-24', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (W)', 'notes_en' => 'Economy class (W)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Miami', 'flight_date' => '2019-06-02', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Miami', 'to_city' => 'İstanbul', 'flight_date' => '2019-06-10', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Stockholm', 'flight_date' => '2019-07-06', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'Stockholm', 'to_city' => 'İstanbul', 'flight_date' => '2019-07-13', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Hamburg', 'flight_date' => '2019-07-30', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (T)', 'notes_en' => 'Economy class (T)'],
            ['from_city' => 'Hamburg', 'to_city' => 'İstanbul', 'flight_date' => '2019-08-09', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (T)', 'notes_en' => 'Economy class (T)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'flight_date' => '2019-08-10', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'Kopenhag', 'to_city' => 'İstanbul', 'flight_date' => '2019-08-24', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Hamburg', 'flight_date' => '2019-08-30', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (T)', 'notes_en' => 'Economy class (T)'],
            ['from_city' => 'Hamburg', 'to_city' => 'İstanbul', 'flight_date' => '2019-09-10', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (T)', 'notes_en' => 'Economy class (T)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Londra', 'flight_date' => '2019-09-18', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (V)', 'notes_en' => 'Economy class (V)'],
            ['from_city' => 'Londra', 'to_city' => 'İstanbul', 'flight_date' => '2019-09-27', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Marsilya', 'flight_date' => '2019-10-05', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (W)', 'notes_en' => 'Economy class (W)'],
            ['from_city' => 'Marsilya', 'to_city' => 'İstanbul', 'flight_date' => '2019-10-13', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (W)', 'notes_en' => 'Economy class (W)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Miami', 'flight_date' => '2019-11-01', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (W)', 'notes_en' => 'Economy class (W)'],
            ['from_city' => 'Miami', 'to_city' => 'İstanbul', 'flight_date' => '2019-11-09', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (W)', 'notes_en' => 'Economy class (W)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Male', 'flight_date' => '2020-01-11', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (E)', 'notes_en' => 'Economy class (E)'],
            ['from_city' => 'Mumbai', 'to_city' => 'İstanbul', 'flight_date' => '2020-01-18', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Business sınıfı (L)', 'notes_en' => 'Business class (L)'],
            ['from_city' => 'Singapur', 'to_city' => 'İstanbul', 'flight_date' => '2020-02-04', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (W)', 'notes_en' => 'Economy class (W)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Miami', 'flight_date' => '2022-01-28', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Miami', 'to_city' => 'İstanbul', 'flight_date' => '2022-02-05', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Cancun', 'flight_date' => '2022-04-13', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (Y)', 'notes_en' => 'Economy class (Y)'],
            ['from_city' => 'Mexico City', 'to_city' => 'İstanbul', 'flight_date' => '2022-04-22', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (S)', 'notes_en' => 'Economy class (S)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Cancun', 'flight_date' => '2022-05-13', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Business sınıfı (K)', 'notes_en' => 'Business class (K)'],
            ['from_city' => 'Cancun', 'to_city' => 'İstanbul', 'flight_date' => '2022-05-16', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Business sınıfı (K)', 'notes_en' => 'Business class (K)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Cancun', 'flight_date' => '2022-05-31', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (V)', 'notes_en' => 'Economy class (V)'],
            ['from_city' => 'Cancun', 'to_city' => 'İstanbul', 'flight_date' => '2022-06-05', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (T)', 'notes_en' => 'Economy class (T)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Havana', 'flight_date' => '2022-06-08', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Havana', 'to_city' => 'İstanbul', 'flight_date' => '2022-06-13', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Havana', 'flight_date' => '2022-06-15', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Business sınıfı (O)', 'notes_en' => 'Business class (O)'],
            ['from_city' => 'Cancun', 'to_city' => 'İstanbul', 'flight_date' => '2022-06-22', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Business sınıfı (O)', 'notes_en' => 'Business class (O)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'flight_date' => '2022-07-17', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Kopenhag', 'to_city' => 'İstanbul', 'flight_date' => '2022-07-24', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'flight_date' => '2022-07-31', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Kopenhag', 'to_city' => 'İstanbul', 'flight_date' => '2022-08-07', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Business sınıfı (G)', 'notes_en' => 'Business class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Havana', 'flight_date' => '2022-08-08', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Business sınıfı (Q)', 'notes_en' => 'Business class (Q)'],
            ['from_city' => 'Cancun', 'to_city' => 'İstanbul', 'flight_date' => '2022-08-14', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Business sınıfı (V)', 'notes_en' => 'Business class (V)'],
            ['from_city' => 'Antalya', 'to_city' => 'İstanbul', 'flight_date' => '2022-10-03', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Business sınıfı (B)', 'notes_en' => 'Business class (B)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Vilnius', 'flight_date' => '2022-10-04', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (V)', 'notes_en' => 'Economy class (V)'],
            ['from_city' => 'Helsinki', 'to_city' => 'İstanbul', 'flight_date' => '2022-10-11', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (P)', 'notes_en' => 'Economy class (P)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Milano', 'flight_date' => '2022-10-28', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (M)', 'notes_en' => 'Economy class (M)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Antalya', 'flight_date' => '2022-11-11', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (B)', 'notes_en' => 'Economy class (B)'],
            ['from_city' => 'Milano', 'to_city' => 'İstanbul', 'flight_date' => '2022-11-11', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Antalya', 'to_city' => 'İstanbul', 'flight_date' => '2022-11-19', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Business sınıfı (B)', 'notes_en' => 'Business class (B)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Milano', 'flight_date' => '2022-11-19', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (P)', 'notes_en' => 'Economy class (P)'],
            ['from_city' => 'Buenos Aires', 'to_city' => 'İstanbul', 'flight_date' => '2022-12-11', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Catania', 'flight_date' => '2023-03-17', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Malta', 'to_city' => 'İstanbul', 'flight_date' => '2023-03-21', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Antalya', 'to_city' => 'İstanbul', 'flight_date' => '2023-04-08', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Marsilya', 'flight_date' => '2023-04-08', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Marsilya', 'to_city' => 'İstanbul', 'flight_date' => '2023-04-22', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Gazipaşa', 'flight_date' => '2023-04-23', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (B)', 'notes_en' => 'Economy class (B)'],
            ['from_city' => 'Antalya', 'to_city' => 'İstanbul', 'flight_date' => '2023-05-05', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Milano', 'flight_date' => '2023-05-05', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (P)', 'notes_en' => 'Economy class (P)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Antalya', 'flight_date' => '2023-05-20', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (Q)', 'notes_en' => 'Economy class (Q)'],
            ['from_city' => 'Kopenhag', 'to_city' => 'İstanbul', 'flight_date' => '2023-05-20', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Antalya', 'to_city' => 'İstanbul', 'flight_date' => '2023-06-01', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (T)', 'notes_en' => 'Economy class (T)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'flight_date' => '2023-06-03', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Kopenhag', 'to_city' => 'İstanbul', 'flight_date' => '2023-06-10', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Antalya', 'flight_date' => '2023-06-10', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (S)', 'notes_en' => 'Economy class (S)'],
            ['from_city' => 'Antalya', 'to_city' => 'İstanbul', 'flight_date' => '2023-06-24', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (S)', 'notes_en' => 'Economy class (S)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'flight_date' => '2023-06-24', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Kopenhag', 'to_city' => 'İstanbul', 'flight_date' => '2023-07-01', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Antalya', 'flight_date' => '2023-07-01', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (T)', 'notes_en' => 'Economy class (T)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'flight_date' => '2023-07-09', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (N)', 'notes_en' => 'Economy class (N)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Antalya', 'flight_date' => '2023-07-16', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (A)', 'notes_en' => 'Economy class (A)'],
            ['from_city' => 'Kopenhag', 'to_city' => 'İstanbul', 'flight_date' => '2023-07-16', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (N)', 'notes_en' => 'Economy class (N)'],
            ['from_city' => 'Antalya', 'to_city' => 'İstanbul', 'flight_date' => '2023-07-29', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (B)', 'notes_en' => 'Economy class (B)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'flight_date' => '2023-07-29', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Kopenhag', 'to_city' => 'İstanbul', 'flight_date' => '2023-08-05', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'flight_date' => '2023-09-02', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Gazipaşa', 'to_city' => 'İstanbul', 'flight_date' => '2023-09-02', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Business sınıfı (B)', 'notes_en' => 'Business class (B)'],
            ['from_city' => 'Kopenhag', 'to_city' => 'İstanbul', 'flight_date' => '2023-09-09', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Antalya', 'flight_date' => '2023-09-09', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (M)', 'notes_en' => 'Economy class (M)'],
            ['from_city' => 'Antalya', 'to_city' => 'İstanbul', 'flight_date' => '2023-09-19', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'Gazipaşa', 'to_city' => 'İstanbul', 'flight_date' => '2023-10-31', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (S)', 'notes_en' => 'Economy class (S)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Marsilya', 'flight_date' => '2023-11-01', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'Marsilya', 'to_city' => 'İstanbul', 'flight_date' => '2023-11-11', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (G)', 'notes_en' => 'Economy class (G)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Antalya', 'flight_date' => '2023-11-12', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (S)', 'notes_en' => 'Economy class (S)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Tokyo', 'flight_date' => '2023-12-20', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'Gazipaşa', 'to_city' => 'İstanbul', 'flight_date' => '2023-12-20', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (O)', 'notes_en' => 'Economy class (O)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Gazipaşa', 'flight_date' => '2024-01-02', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (Q)', 'notes_en' => 'Economy class (Q)'],
            ['from_city' => 'Tokyo', 'to_city' => 'İstanbul', 'flight_date' => '2024-01-02', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Rovaniemi', 'flight_date' => '2024-01-28', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (T)', 'notes_en' => 'Economy class (T)'],
            ['from_city' => 'Rovaniemi', 'to_city' => 'İstanbul', 'flight_date' => '2024-02-01', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (Q)', 'notes_en' => 'Economy class (Q)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Rovaniemi', 'flight_date' => '2024-02-04', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (H)', 'notes_en' => 'Economy class (H)'],
            ['from_city' => 'Antalya', 'to_city' => 'İstanbul', 'flight_date' => '2024-02-15', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (W)', 'notes_en' => 'Economy class (W)'],
            ['from_city' => 'Gazipaşa', 'to_city' => 'İstanbul', 'flight_date' => '2024-02-29', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (V)', 'notes_en' => 'Economy class (V)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Catania', 'flight_date' => '2024-03-01', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (V)', 'notes_en' => 'Economy class (V)'],
            ['from_city' => 'Malta', 'to_city' => 'İstanbul', 'flight_date' => '2024-03-05', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Antalya', 'flight_date' => '2024-03-06', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (V)', 'notes_en' => 'Economy class (V)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Marsilya', 'flight_date' => '2024-05-18', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (V)', 'notes_en' => 'Economy class (V)'],
            ['from_city' => 'Marsilya', 'to_city' => 'İstanbul', 'flight_date' => '2024-05-25', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (V)', 'notes_en' => 'Economy class (V)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Gazipaşa', 'flight_date' => '2024-05-26', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Business sınıfı (T)', 'notes_en' => 'Business class (T)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Londra', 'flight_date' => '2024-07-26', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (V)', 'notes_en' => 'Economy class (V)'],
            ['from_city' => 'Londra', 'to_city' => 'İstanbul', 'flight_date' => '2024-08-08', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (E)', 'notes_en' => 'Economy class (E)'],
            ['from_city' => 'Gazipaşa', 'to_city' => 'İstanbul', 'flight_date' => '2024-09-25', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (S)', 'notes_en' => 'Economy class (S)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Palermo', 'flight_date' => '2024-09-26', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (P)', 'notes_en' => 'Economy class (P)'],
            ['from_city' => 'Catania', 'to_city' => 'İstanbul', 'flight_date' => '2024-09-30', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (P)', 'notes_en' => 'Economy class (P)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Malta', 'flight_date' => '2024-10-26', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (B)', 'notes_en' => 'Economy class (B)'],
            ['from_city' => 'Malta', 'to_city' => 'İstanbul', 'flight_date' => '2024-10-30', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Business sınıfı (V)', 'notes_en' => 'Business class (V)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Torino', 'flight_date' => '2024-11-09', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (P)', 'notes_en' => 'Economy class (P)'],
            ['from_city' => 'Nice', 'to_city' => 'İstanbul', 'flight_date' => '2024-11-16', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (P)', 'notes_en' => 'Economy class (P)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Barselona', 'flight_date' => '2024-11-22', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (P)', 'notes_en' => 'Economy class (P)'],
            ['from_city' => 'Antalya', 'to_city' => 'İstanbul', 'flight_date' => '2024-11-22', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Business sınıfı (B)', 'notes_en' => 'Business class (B)'],
            ['from_city' => 'Barselona', 'to_city' => 'İstanbul', 'flight_date' => '2024-11-29', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Gazipaşa', 'flight_date' => '2024-11-30', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (T)', 'notes_en' => 'Economy class (T)'],
            ['from_city' => 'Gazipaşa', 'to_city' => 'İstanbul', 'flight_date' => '2024-12-06', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (S)', 'notes_en' => 'Economy class (S)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Gazipaşa', 'flight_date' => '2024-12-17', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (V)', 'notes_en' => 'Economy class (V)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Rovaniemi', 'flight_date' => '2025-01-19', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'Rovaniemi', 'to_city' => 'İstanbul', 'flight_date' => '2025-01-23', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'Gazipaşa', 'to_city' => 'İstanbul', 'flight_date' => '2025-02-25', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (V)', 'notes_en' => 'Economy class (V)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Sao Paulo', 'flight_date' => '2025-02-26', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Buenos Aires', 'flight_date' => '2025-02-26', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'Buenos Aires', 'to_city' => 'Sao Paulo', 'flight_date' => '2025-03-10', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'Buenos Aires', 'to_city' => 'İstanbul', 'flight_date' => '2025-03-10', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Business sınıfı (L)', 'notes_en' => 'Business class (L)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Tokyo', 'flight_date' => '2025-03-31', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'Antalya', 'to_city' => 'İstanbul', 'flight_date' => '2025-03-31', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (T)', 'notes_en' => 'Economy class (T)'],
            ['from_city' => 'Osaka', 'to_city' => 'İstanbul', 'flight_date' => '2025-04-08', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (O)', 'notes_en' => 'Economy class (O)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Hamburg', 'flight_date' => '2025-05-03', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Business sınıfı (P)', 'notes_en' => 'Business class (P)'],
            ['from_city' => 'Hamburg', 'to_city' => 'İstanbul', 'flight_date' => '2025-05-10', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (P)', 'notes_en' => 'Economy class (P)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Antalya', 'flight_date' => '2025-05-11', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (E)', 'notes_en' => 'Economy class (E)'],
            ['from_city' => 'Gazipaşa', 'to_city' => 'İstanbul', 'flight_date' => '2025-05-15', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (T)', 'notes_en' => 'Economy class (T)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'flight_date' => '2025-05-17', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Business sınıfı (Q)', 'notes_en' => 'Business class (Q)'],
            ['from_city' => 'Kopenhag', 'to_city' => 'İstanbul', 'flight_date' => '2025-05-24', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Business sınıfı (V)', 'notes_en' => 'Business class (V)'],
            ['from_city' => 'İstanbul', 'to_city' => 'St. Petersburg', 'flight_date' => '2025-06-02', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (T)', 'notes_en' => 'Economy class (T)'],
            ['from_city' => 'Moskova', 'to_city' => 'İstanbul', 'flight_date' => '2025-06-10', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (E)', 'notes_en' => 'Economy class (E)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Londra', 'flight_date' => '2025-07-02', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (U)', 'notes_en' => 'Economy class (U)'],
            ['from_city' => 'Londra', 'to_city' => 'İstanbul', 'flight_date' => '2025-07-17', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (E)', 'notes_en' => 'Economy class (E)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Kopenhag', 'flight_date' => '2025-08-04', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Business sınıfı (Y)', 'notes_en' => 'Business class (Y)'],
            ['from_city' => 'Antalya', 'to_city' => 'İstanbul', 'flight_date' => '2025-08-04', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Business sınıfı (B)', 'notes_en' => 'Business class (B)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Antalya', 'flight_date' => '2025-08-11', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (A)', 'notes_en' => 'Economy class (A)'],
            ['from_city' => 'Stockholm', 'to_city' => 'İstanbul', 'flight_date' => '2025-08-11', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (U)', 'notes_en' => 'Economy class (U)'],
            ['from_city' => 'Antalya', 'to_city' => 'İstanbul', 'flight_date' => '2025-08-21', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (O)', 'notes_en' => 'Economy class (O)'],
            ['from_city' => 'Antalya', 'to_city' => 'İstanbul', 'flight_date' => '2025-09-11', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (V)', 'notes_en' => 'Economy class (V)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Antalya', 'flight_date' => '2025-09-18', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (L)', 'notes_en' => 'Economy class (L)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Roma', 'flight_date' => '2025-10-23', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (V)', 'notes_en' => 'Economy class (V)'],
            ['from_city' => 'Antalya', 'to_city' => 'İstanbul', 'flight_date' => '2025-10-23', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (D)', 'notes_en' => 'Economy class (D)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Gazipaşa', 'flight_date' => '2025-10-30', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (O)', 'notes_en' => 'Economy class (O)'],
            ['from_city' => 'Gazipaşa', 'to_city' => 'İstanbul', 'flight_date' => '2025-11-21', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (Q)', 'notes_en' => 'Economy class (Q)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Tokyo', 'flight_date' => '2025-11-24', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (O)', 'notes_en' => 'Economy class (O)'],
            ['from_city' => 'Osaka', 'to_city' => 'İstanbul', 'flight_date' => '2025-12-02', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (V)', 'notes_en' => 'Economy class (V)'],
            ['from_city' => 'Antalya', 'to_city' => 'İstanbul', 'flight_date' => '2025-12-26', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (P)', 'notes_en' => 'Economy class (P)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Hanoi', 'flight_date' => '2026-03-12', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (U)', 'notes_en' => 'Economy class (U)'],
            ['from_city' => 'Ho Chi Minh', 'to_city' => 'İstanbul', 'flight_date' => '2026-03-22', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (U)', 'notes_en' => 'Economy class (U)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Cape Town', 'flight_date' => '2026-04-04', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (U)', 'notes_en' => 'Economy class (U)'],
            ['from_city' => 'Johannesburg', 'to_city' => 'İstanbul', 'flight_date' => '2026-04-16', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (T)', 'notes_en' => 'Economy class (T)'],
            ['from_city' => 'İstanbul', 'to_city' => 'Edinburgh', 'flight_date' => '2026-06-01', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (B)', 'notes_en' => 'Economy class (B)'],
            ['from_city' => 'Londra', 'to_city' => 'İstanbul', 'flight_date' => '2026-06-07', 'airline' => 'Turkish Airlines', 'notes_tr' => 'Ekonomi sınıfı (V)', 'notes_en' => 'Economy class (V)'],
        ];

        foreach ($flights as $flight) {
            Flight::create($flight);
        }
    }
}
